from pathlib import Path
import json
p=Path('assets/js/nx-v157-primary-school-script.js')
s=p.read_text(encoding='utf-8')
s=s.replace('École primaire interactive V603','École primaire interactive V604',1)
s=s.replace("var VERSION = 'v603';","var VERSION = 'v604';",1)
s=s.replace('window.__nxPrimaryExercisesV603','window.__nxPrimaryExercisesV604')
start=s.index('    sciences: [')
end=s.index('\n\n    ecm: [',start)
science=r'''    sciences: [
      cp1Lesson('Vivant ou non vivant ?',
        'Un animal et une plante sont vivants. Ils ont des besoins et ils changent en grandissant. Une pierre, une chaise ou une cuillère ne sont pas vivantes.',
        'Ne décide pas seulement parce qu’une chose bouge. Une voiture peut bouger, mais elle ne grandit pas comme un animal ou une plante. Il faut regarder plusieurs indices.',
        'Exemple : la chèvre mange et grandit. La pierre ne mange pas et ne grandit pas.',
        '🐐  🌱  🪨  🪑','Chèvre, plante, pierre et chaise',[
          q('Lequel est vivant ?',['la chèvre','la pierre','la chaise'],'la chèvre','La chèvre est un animal vivant.'),
          q('Lequel est une plante vivante ?',['le manguier','la table','la bouteille'],'le manguier','Le manguier pousse et se développe.'),
          q('Une voiture bouge. Est-elle vivante ?',['Non','Oui, parce qu’elle bouge'],'Non','Bouger ne suffit pas pour être vivant.'),
          q('Quel indice aide le mieux ?',['Grandir et avoir des besoins','Être rouge','Être en métal'],'Grandir et avoir des besoins','On utilise plusieurs signes du vivant.')]),
      cp1Lesson('La diversité autour de nous',
        'Autour de nous, il y a des personnes, des animaux et des plantes. Dans une cour, un village ou un quartier, nous pouvons observer plusieurs formes de vie.',
        'Observer la diversité, c’est regarder les différences : un manguier n’est pas une herbe, une poule n’est pas une chèvre. Pourtant, tous peuvent être vivants.',
        'Exemple : 👧🏾, 🐔 et 🌳 sont trois êtres vivants différents.',
        '👧🏾  🐔  🐐  🌳  🌿','Personne, animaux et plantes',[
          q('Quel groupe contient seulement des êtres vivants ?',['enfant, poule, manguier','pierre, table, bouteille','chaise, sac, route'],'enfant, poule, manguier','Les trois éléments sont vivants.'),
          q('Une poule et une chèvre sont :',['deux animaux différents','deux plantes','deux pierres'],'deux animaux différents','Elles appartiennent toutes les deux au monde animal.'),
          q('Un manguier et une herbe sont :',['deux plantes différentes','deux animaux','deux objets techniques'],'deux plantes différentes','Les plantes peuvent avoir des formes différentes.'),
          q('Pourquoi observer plusieurs êtres vivants ?',['Pour voir leur diversité','Pour dire qu’ils sont tous identiques','Pour répondre au hasard'],'Pour voir leur diversité','Comparer aide à reconnaître ressemblances et différences.')]),
      cp1Lesson('Les grandes parties du corps',
        'Ton corps comprend la tête, le tronc et les membres. Les bras et les jambes sont des membres. Sur la tête, tu trouves les yeux, les oreilles, le nez et la bouche.',
        'Pour nommer une partie du corps, regarde sa place. La main est au bout du bras. Le pied est au bout de la jambe. La position aide à reconnaître.',
        'Exemple : tête → tronc → jambes.',
        '🧒🏾  👁️  👂🏾  👃🏾  ✋🏾  🦶🏾','Corps et principales parties',[
          q('Quelle partie est sur la tête ?',['les yeux','les pieds','les genoux'],'les yeux','Les yeux sont situés sur le visage.'),
          q('La main est au bout :',['du bras','de la tête','du nez'],'du bras','La main prolonge le membre supérieur.'),
          q('Le pied est au bout :',['de la jambe','du bras','de l’oreille'],'de la jambe','Le pied se trouve à l’extrémité de la jambe.'),
          q('Pourquoi regarder la place d’une partie ?',['Pour mieux l’identifier','Pour changer son nom','Pour compter les jours'],'Pour mieux l’identifier','La position donne un indice utile.')]),
      cp1Lesson('Les yeux et la vue',
        'Les yeux permettent de voir la lumière, les couleurs, les formes et les objets. Nous utilisons la vue pour observer ce qui est devant nous.',
        'Voir ne veut pas dire tout savoir. Si un objet est loin ou caché, l’œil peut manquer une information. Il faut parfois se rapprocher sans danger ou demander une aide.',
        'Exemple : tu vois un feu rouge et tu t’arrêtes avec l’adulte qui t’accompagne.',
        '👀  🔴  🔵  🟩','Yeux et couleurs',[
          q('Avec quoi vois-tu ?',['les yeux','les oreilles','la langue'],'les yeux','Les yeux sont les organes de la vue.'),
          q('La vue aide à reconnaître :',['les couleurs','le goût seul','un son sans regarder'],'les couleurs','Les couleurs sont perçues par les yeux.'),
          q('Un objet est caché derrière un mur. Peux-tu toujours le voir ?',['Non','Oui, toujours'],'Non','Un obstacle peut empêcher la vue.'),
          q('Que fais-tu si tu ne vois pas bien une consigne au tableau ?',['Je le dis au maître','Je devine toujours','Je ferme les yeux'],'Je le dis au maître','Demander de l’aide est une bonne décision.')]),
      cp1Lesson('Les oreilles et les sons',
        'Les oreilles permettent d’entendre. Tu peux entendre une voix, un tambour, un klaxon ou un oiseau.',
        'Un son peut donner une information même si tu ne vois pas sa source. Un klaxon peut t’alerter. Il faut écouter et réfléchir avant d’agir.',
        'Exemple : tu entends une voiture arriver avant de la voir.',
        '👂🏾  🥁  🚗  🐦','Oreille et sources sonores',[
          q('Avec quoi entends-tu ?',['les oreilles','les yeux','les pieds'],'les oreilles','Les oreilles servent à l’audition.'),
          q('Lequel produit un son ?',['un tambour frappé','une pierre immobile sans choc','une couleur'],'un tambour frappé','Le tambour produit un son quand il est frappé.'),
          q('Tu entends un klaxon. Que peut-il t’indiquer ?',['Un véhicule est peut-être proche','Le riz est sucré','La nuit est verte'],'Un véhicule est peut-être proche','Le son peut signaler une présence ou un danger.'),
          q('Pourquoi écouter autour de soi ?',['Pour recevoir des informations','Pour fermer les yeux toujours','Pour changer les sons'],'Pour recevoir des informations','L’ouïe aide à comprendre l’environnement.')]),
      cp1Lesson('Le nez et les odeurs',
        'Le nez permet de sentir les odeurs. Une fleur, un savon, un aliment ou de la fumée peuvent avoir une odeur.',
        'Une odeur peut être agréable ou désagréable. Elle peut aussi avertir. Si tu sens une forte odeur de fumée, préviens un adulte et éloigne-toi du danger.',
        'Exemple : 🌼 peut sentir bon ; de la fumée peut signaler un risque.',
        '👃🏾  🌼  🧼  💨','Nez, fleur, savon et fumée',[
          q('Avec quoi sens-tu une odeur ?',['le nez','les yeux','les pieds'],'le nez','Le nez est l’organe de l’odorat.'),
          q('Quel objet peut avoir une odeur parfumée ?',['une fleur','un nombre','une ligne'],'une fleur','Beaucoup de fleurs émettent des odeurs.'),
          q('Tu sens beaucoup de fumée. Que fais-tu ?',['Je préviens un adulte et je m’éloigne','Je cherche à respirer plus de fumée','Je me cache dans la fumée'],'Je préviens un adulte et je m’éloigne','Une odeur peut signaler un danger.'),
          q('Une odeur donne-t-elle une information ?',['Oui','Non, jamais'],'Oui','L’odorat nous informe sur ce qui nous entoure.')]),
      cp1Lesson('La langue et les goûts',
        'La langue participe au goût. Nous pouvons reconnaître des goûts comme sucré, salé, amer ou acide.',
        'Il ne faut pas goûter un produit inconnu pour savoir ce qu’il est. Certaines substances peuvent être dangereuses. On goûte seulement les aliments autorisés par un adulte responsable.',
        'Exemple : le sucre est sucré ; le sel est salé.',
        '👅  🍬  🧂  🍋','Langue et aliments de goûts différents',[
          q('Quel organe participe au goût ?',['la langue','l’oreille','le coude'],'la langue','La langue contient des récepteurs du goût.'),
          q('Le sucre est surtout :',['sucré','salé','amer'],'sucré','Le sucre donne une sensation sucrée.'),
          q('Le sel est surtout :',['salé','sucré','sans aucun goût'],'salé','Le sel donne une sensation salée.'),
          q('Peux-tu goûter un produit inconnu trouvé par terre ?',['Non','Oui toujours'],'Non','On ne goûte pas une substance inconnue : elle peut être dangereuse.')]),
      cp1Lesson('La peau et le toucher',
        'La peau nous aide à sentir le contact, la texture et certaines températures. Avec la main, tu peux reconnaître quelque chose de doux ou rugueux.',
        'Le toucher donne des informations, mais il faut respecter la sécurité. Ne touche jamais une flamme, un fil électrique abîmé ou un objet très chaud.',
        'Exemple : un tissu peut être doux ; une pierre peut être rugueuse.',
        '✋🏾  🧸  🪨  🔥','Main, objet doux, pierre et feu',[
          q('Quel organe couvre ton corps et participe au toucher ?',['la peau','les cheveux seulement','les dents'],'la peau','La peau contient des récepteurs sensibles au contact.'),
          q('Lequel peut être rugueux ?',['une pierre','un coussin doux','de l’air'],'une pierre','Beaucoup de pierres ont une surface irrégulière.'),
          q('Faut-il toucher une casserole très chaude ?',['Non','Oui'],'Non','La chaleur peut brûler la peau.'),
          q('Pourquoi le toucher doit-il rester prudent ?',['Certains objets peuvent blesser','Tout objet est sans danger','Pour ne jamais utiliser les mains'],'Certains objets peuvent blesser','On utilise le sens du toucher avec des règles de sécurité.')]),
      cp1Lesson('Les animaux de notre milieu',
        'Dans notre milieu, on peut rencontrer la chèvre, la vache, le chien, le chat, la poule et d’autres animaux. Ils n’ont pas tous la même taille ni le même mode de vie.',
        'Pour reconnaître un animal, observe sa forme, ses pattes, son pelage ou ses plumes, son alimentation et l’endroit où il vit.',
        'Exemple : la poule a des plumes ; la chèvre a des poils.',
        '🐐  🐄  🐕  🐈  🐔','Animaux domestiques courants',[
          q('Lequel est un animal ?',['la chèvre','le manguier','la chaise'],'la chèvre','La chèvre appartient au monde animal.'),
          q('Quel animal a des plumes ?',['la poule','la chèvre','le chat'],'la poule','Les oiseaux comme la poule portent des plumes.'),
          q('Quel indice aide à reconnaître un animal ?',['Son corps et son mode de vie','La couleur du cahier','Le jour de la semaine'],'Son corps et son mode de vie','Plusieurs caractéristiques permettent l’identification.'),
          q('Tous les animaux sont-ils identiques ?',['Non','Oui'],'Non','Ils présentent une grande diversité.')]),
      cp1Lesson('Prendre soin d’un animal',
        'Un animal domestique a besoin d’eau, de nourriture, d’un lieu adapté et de soins. Il ne faut pas le frapper ni le faire souffrir.',
        'Prendre soin, c’est observer ses besoins. Un animal qui n’a pas d’eau ou qui semble malade doit être signalé à un adulte responsable.',
        'Exemple : donner de l’eau propre à une chèvre et garder son espace propre.',
        '🐐  💧  🌾  🏡','Animal avec eau, nourriture et abri',[
          q('Un animal domestique a besoin :',['d’eau et de nourriture','de plastique à manger','de fumée'],'d’eau et de nourriture','L’eau et la nourriture font partie de ses besoins.'),
          q('Que fais-tu si l’animal semble malade ?',['Je préviens un adulte','Je le frappe','Je l’ignore toujours'],'Je préviens un adulte','Un adulte peut chercher les soins adaptés.'),
          q('Faut-il faire souffrir un animal ?',['Non','Oui'],'Non','Le respect du vivant inclut le bien-être animal.'),
          q('Pourquoi garder son espace propre ?',['Pour l’hygiène et la santé','Pour salir l’eau','Pour cacher l’animal'],'Pour l’hygiène et la santé','Un milieu propre réduit certains risques sanitaires.')]),
      cp1Lesson('Les parties d’une plante',
        'Une plante peut avoir des racines, une tige, des feuilles, des fleurs et des fruits. Les racines sont généralement dans le sol.',
        'Chaque partie a une place et un rôle. Les racines fixent la plante et prennent de l’eau dans le sol. Les feuilles reçoivent la lumière.',
        'Exemple : 🌱 racines en bas, tige au milieu, feuilles autour.',
        '🌱  🌿  🌼  🥭','Plante, feuilles, fleur et fruit',[
          q('Quelle partie est généralement dans le sol ?',['les racines','les feuilles','les fleurs'],'les racines','Les racines se développent généralement dans le sol.'),
          q('Quelle partie porte souvent les feuilles ?',['la tige','la pierre','la route'],'la tige','La tige soutient les parties aériennes.'),
          q('Un fruit peut venir :',['d’une plante','d’une chaise','d’un caillou'],'d’une plante','Les fruits sont produits par certaines plantes.'),
          q('Pourquoi observer chaque partie ?',['Pour comprendre l’organisation de la plante','Pour dire qu’elles sont toutes pareilles','Pour changer sa couleur'],'Pour comprendre l’organisation de la plante','Décomposer permet de mieux comprendre un être vivant.')]),
      cp1Lesson('Les plantes fruitières de chez nous',
        'Dans notre milieu, nous pouvons voir le manguier, l’oranger, le bananier, le goyavier, le palmier et d’autres plantes utiles.',
        'Relie le fruit à la plante qui le produit. Une mangue vient du manguier. Une orange vient de l’oranger. Ne mélange pas le nom du fruit et celui de la plante.',
        'Exemple : manguier → mangue ; oranger → orange.',
        '🌳🥭  🌳🍊  🌴  🍌','Arbres et fruits',[
          q('La mangue vient :',['du manguier','de la pierre','du savon'],'du manguier','Le manguier produit des mangues.'),
          q('L’orange vient :',['de l’oranger','du riz','de la table'],'de l’oranger','L’oranger produit des oranges.'),
          q('Le bananier produit :',['des bananes','des cahiers','des poissons'],'des bananes','La banane est le fruit du bananier.'),
          q('Pourquoi relier fruit et plante ?',['Pour comprendre leur origine','Pour changer le goût','Pour compter les routes'],'Pour comprendre leur origine','Cette relation aide à comprendre le milieu vivant.')]),
      cp1Lesson('Les aliments et leur origine',
        'Nous mangeons des aliments d’origine végétale et animale. Le riz et la mangue viennent des plantes. Le lait et les œufs viennent d’animaux.',
        'Pour classer un aliment, demande-toi d’où il vient avant d’arriver dans l’assiette. Cette question aide à comprendre la production de nos aliments.',
        'Exemple : 🌾 → riz ; 🐔 → œuf.',
        '🍚  🥭  🥚  🥛','Riz, mangue, œuf et lait',[
          q('Le riz est surtout d’origine :',['végétale','minérale','plastique'],'végétale','Le riz est une graine produite par une plante.'),
          q('L’œuf vient :',['d’un animal','d’une pierre','d’un cahier'],'d’un animal','Des animaux comme la poule pondent des œufs.'),
          q('La mangue est d’origine :',['végétale','métallique','animale'],'végétale','Elle pousse sur le manguier.'),
          q('Quelle question aide à classer un aliment ?',['D’où vient-il ?','Quelle est ma couleur préférée ?','Quel jour sommes-nous ?'],'D’où vient-il ?','Chercher l’origine permet un classement raisonné.')]),
      cp1Lesson('Propreté du corps et des vêtements',
        'Pour rester propre, nous lavons le corps, les mains et les vêtements. Des ongles propres et des habits propres participent à une bonne hygiène.',
        'L’hygiène est une habitude régulière. Attendre d’être très sale n’est pas une bonne méthode. On se lave après certaines activités et avant de manger.',
        'Exemple : se laver les mains avec de l’eau propre et du savon avant le repas.',
        '🧼  👐🏾  👕  🚿','Savon, mains, vêtement et douche',[
          q('Avant de manger, il est utile de :',['se laver les mains','salir les mains','toucher les déchets'],'se laver les mains','Le lavage des mains aide à réduire les microbes.'),
          q('Des vêtements propres participent :',['à l’hygiène','à salir le corps','à rendre l’eau dangereuse'],'à l’hygiène','La propreté des vêtements fait partie des soins du corps.'),
          q('Quand faut-il se laver ?',['régulièrement et après certaines activités','jamais','seulement une fois dans l’année'],'régulièrement et après certaines activités','L’hygiène repose sur des habitudes répétées.'),
          q('Pourquoi utiliser du savon quand c’est possible ?',['Il aide à enlever saletés et microbes','Il remplace l’eau à boire','Il sert à écrire'],'Il aide à enlever saletés et microbes','Le savon améliore le nettoyage des mains et du corps.')]),
      cp1Lesson('Prendre soin de ses dents',
        'Les dents servent notamment à couper et mâcher les aliments. Elles doivent être brossées régulièrement avec une brosse adaptée et du dentifrice si disponible.',
        'Après avoir mangé, des restes peuvent rester sur les dents. Le brossage aide à les enlever. Trop de produits très sucrés peut favoriser les problèmes dentaires.',
        'Exemple : brosser doucement toutes les faces des dents.',
        '🦷  🪥  😁','Dent et brosse à dents',[
          q('Quel objet sert à brosser les dents ?',['une brosse à dents','un balai','une règle'],'une brosse à dents','Elle est conçue pour nettoyer les dents.'),
          q('Pourquoi se brosser les dents ?',['Pour enlever des restes et protéger les dents','Pour les salir','Pour les rendre invisibles'],'Pour enlever des restes et protéger les dents','Le brossage participe à la santé bucco-dentaire.'),
          q('Faut-il brosser seulement une petite partie des dents ?',['Non','Oui'],'Non','Il faut nettoyer les différentes faces accessibles.'),
          q('Que peut faire un excès fréquent de produits très sucrés ?',['Favoriser des problèmes dentaires','Renforcer toujours toutes les dents','Remplacer le brossage'],'Favoriser des problèmes dentaires','Le sucre fréquent favorise le risque de caries.')]),
      cp1Lesson('Hygiène des aliments et de l’eau',
        'Avant de manger un fruit, il faut le laver avec une eau propre. Les aliments doivent être protégés de la saleté. L’eau à boire doit être sûre.',
        'Regarde les signes de risque : eau visiblement sale, aliment tombé dans un endroit sale, nourriture mal protégée. En cas de doute, demande à un adulte.',
        'Exemple : laver une mangue avant de la manger.',
        '💧  🥭  🧼  ✅','Eau propre et fruit lavé',[
          q('Avant de manger une mangue, tu dois :',['la laver','la rouler dans la poussière','la poser dans les déchets'],'la laver','Le lavage aide à enlever des saletés.'),
          q('Une eau est visiblement sale. Tu :',['ne la bois pas et tu préviens un adulte','la bois vite','ajoutes du sable'],'ne la bois pas et tu préviens un adulte','Une eau sale peut présenter un risque sanitaire.'),
          q('Pourquoi couvrir certains aliments ?',['Pour les protéger des saletés et insectes','Pour les rendre plus lourds','Pour les transformer en pierre'],'Pour les protéger des saletés et insectes','La protection réduit certaines contaminations.'),
          q('Tu as un doute sur un aliment. Que fais-tu ?',['Je demande à un adulte responsable','Je le mange toujours','Je le donne à un petit enfant'],'Je demande à un adulte responsable','En cas de doute sanitaire, l’aide d’un adulte est la bonne décision.')]),
      cp1Lesson('Garder la maison et l’école propres',
        'Nous gardons la cour, la classe et la maison propres. Les déchets vont dans un endroit prévu. Nous évitons l’eau stagnante et les saletés autour des lieux de vie.',
        'Un petit geste répété par tout le monde devient important. Si chacun jette un papier au sol, la cour devient sale. Si chacun range et jette correctement, le lieu reste plus propre.',
        'Exemple : ramasser un papier et le mettre dans la poubelle ou le dispositif prévu.',
        '🏫  🏠  🗑️  🧹','École, maison, poubelle et balai',[
          q('Un papier est au sol. Que fais-tu si un endroit pour les déchets est disponible ?',['Je le mets au bon endroit','Je le disperse','Je le cache sous une table'],'Je le mets au bon endroit','Le déchet doit être géré proprement.'),
          q('Pourquoi éviter l’eau stagnante autour de la maison ?',['Elle peut favoriser certains risques sanitaires','Elle rend toujours la maison plus belle','Elle remplace l’eau potable'],'Elle peut favoriser certains risques sanitaires','Un environnement bien entretenu participe à la santé.'),
          q('Si tous les élèves jettent au sol, la cour devient :',['plus sale','automatiquement propre','plus petite'],'plus sale','Les actions individuelles s’additionnent.'),
          q('Quel comportement protège le lieu commun ?',['Ranger et nettoyer','Casser les poubelles','Jeter partout'],'Ranger et nettoyer','Prendre soin du milieu est une responsabilité partagée.')]),
      cp1Lesson('Sécurité à la maison et sur la route',
        'À la maison, certains objets sont dangereux : feu, médicaments, produits inconnus, prises électriques. Sur la route, un enfant s’arrête, observe et suit les consignes de l’adulte qui l’accompagne.',
        'Avant d’agir, cherche le danger. Un objet peut sembler intéressant mais être brûlant ou toxique. Une route peut sembler vide mais un véhicule peut arriver vite.',
        'Exemple : ne jamais jouer avec une prise électrique ou une flamme.',
        '🔥  🔌  🚗  🚸','Feu, prise et traversée de route',[
          q('Peux-tu jouer avec une prise électrique ?',['Non','Oui'],'Non','L’électricité peut provoquer des blessures graves.'),
          q('Un médicament inconnu est posé sur une table. Tu :',['n’y touches pas et préviens un adulte','le goûtes','le donnes à un camarade'],'n’y touches pas et préviens un adulte','Les médicaments ne sont pas des jouets.'),
          q('Avant de traverser une route, tu dois :',['t’arrêter et observer avec l’adulte','courir sans regarder','fermer les yeux'],'t’arrêter et observer avec l’adulte','La prudence permet de repérer les véhicules.'),
          q('Pourquoi une route apparemment vide peut-elle rester dangereuse ?',['Un véhicule peut arriver rapidement','Les routes dorment','Parce que les nombres changent'],'Un véhicule peut arriver rapidement','Il faut anticiper un danger possible.')]),
      cp1Lesson('Objets naturels et objets fabriqués',
        'Une pierre et une branche existent dans la nature. Une chaise, une cuillère et un vélo sont fabriqués ou transformés par l’être humain. Chaque objet peut avoir une fonction.',
        'Pour classer, demande : vient-il directement de la nature ou a-t-il été fabriqué ? Puis demande : à quoi sert-il ? Un outil est choisi selon le travail.',
        'Exemple : marteau → frapper un clou ; cuillère → prendre certains aliments.',
        '🪨  🌿  🔨  🥄  🚲','Objets naturels et techniques',[
          q('Lequel est naturel ?',['une pierre','une chaise','un vélo'],'une pierre','La pierre existe dans la nature.'),
          q('Lequel est fabriqué par l’être humain ?',['une chaise','une feuille d’arbre','un caillou'],'une chaise','La chaise est un objet technique fabriqué.'),
          q('Quel outil peut servir à enfoncer un clou ?',['un marteau','une assiette','une fleur'],'un marteau','Le marteau est adapté à cette tâche.'),
          q('Une casserole très chaude doit être touchée à main nue ?',['Non','Oui'],'Non','Un objet chaud peut provoquer une brûlure.')]),
      cp1Lesson('L’eau et le bois : ressources utiles',
        'L’eau sert à boire quand elle est sûre, à laver et à d’autres usages. Le bois peut servir à fabriquer certains objets ou comme matériau. Ces ressources doivent être utilisées avec soin.',
        'Une ressource n’est pas illimitée. Fermer un robinet ou éviter de gaspiller l’eau est un bon geste. Pour le bois, protéger les arbres et éviter le gaspillage aide le milieu.',
        'Exemple : utiliser seulement l’eau nécessaire pour se laver les mains.',
        '💧  🌳  🪵  🪑','Eau, arbre, bois et objet en bois',[
          q('Quelle ressource sert à boire quand elle est potable ?',['l’eau','le sable','la fumée'],'l’eau','L’eau sûre est indispensable à la vie.'),
          q('Le bois vient principalement :',['des arbres','des poissons','des nuages'],'des arbres','Le bois est une matière d’origine végétale.'),
          q('Pourquoi éviter de gaspiller l’eau ?',['C’est une ressource utile','Pour la rendre sale','Parce qu’elle ne sert à rien'],'C’est une ressource utile','Une utilisation responsable protège les ressources.'),
          q('Quel objet peut être fabriqué en bois ?',['une chaise','une goutte de pluie','une flamme'],'une chaise','Le bois peut servir de matériau de fabrication.')]),
      cp1Lesson('Petit projet : observer, préparer, réaliser',
        'Un petit projet suit des étapes simples. Par exemple, pour planter une graine avec l’adulte : choisir l’endroit, préparer le matériel, mettre la graine, arroser sans excès et observer.',
        'Avant de commencer, demande : quel est mon objectif ? de quoi ai-je besoin ? quelles étapes dois-je suivre ? Après, regarde le résultat et explique ce qui a changé.',
        'Exemple : planter un haricot dans un récipient adapté et observer sa croissance avec l’enseignant.',
        '🌱  🪴  💧  👀','Petit projet de plantation',[
          q('Avant un projet, il faut d’abord :',['savoir ce qu’on veut faire','agir au hasard','cacher le matériel'],'savoir ce qu’on veut faire','Un objectif clair guide les étapes.'),
          q('Pour planter une graine, quel élément est utile ?',['un peu d’eau','du plastique à manger','de la fumée'],'un peu d’eau','L’eau fait partie des besoins de la plante.'),
          q('Après avoir planté, que peux-tu faire ?',['Observer les changements','Oublier toujours le projet','Arracher chaque jour la graine'],'Observer les changements','L’observation permet de suivre l’évolution.'),
          q('Pourquoi travailler par étapes ?',['Pour mieux organiser et vérifier le travail','Pour rendre la tâche confuse','Pour ne rien comprendre'],'Pour mieux organiser et vérifier le travail','Une démarche ordonnée développe l’autonomie et le raisonnement.')])
    ],'''
s=s[:start]+science+s[end:]
p.write_text(s,encoding='utf-8')
Path('version.json').write_text(json.dumps({'version':'V604','message':'Nexora V604 : Sciences d observation CP1 completes en 20 lecons avec audio, illustrations, francais simple et exercices de raisonnement.','critical':False},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('V604 science migration ready')
